
repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format
    rev: v0.1.3
-   repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy csv_extractor
        language: system
        types: [python]
        pass_filenames: false
